CREATE TABLE item_details
(
    id            integer generated by default as identity,
    item_name     varchar UNIQUE NOT NULL,
    total_qty     INTEGER        not null,
    sold_qty      INTEGER        not null,
    supplier_desc varchar,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    status        varchar(20),
    price         INTEGER        not null

);